name: deployment to production server

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: update chat bot
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd /home/mark/chat_bot
            git pull origin master
            cat << WRITEDATA >> .env
            BOT_TOKEN = "${{ secrets.ENV_BOT_TOKEN }}"
            CHAT_ID = "${{ secrets.ENV_CHAT_ID }}"
            ADMINS = "${{ secrets.ENV_ADMINS }}"
            WRITEDATA
            docker-compose up -d --build
